name: Build Container

on:
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  docker_build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to container registry
        run: |
          echo $CONTAINER_TOKEN | docker login ghcr.io -u theislab --password-stdin
        env:
          CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
      -
        name: Build and run container
        run: |
          docker build . -t ghcr.io/theislab/extended-single-cell-best-practices-container:latest
          docker run ghcr.io/theislab/extended-single-cell-best-practices-container:latest
