name: Publish Container

on:
  release:
    types: [published]

jobs:
  docker_publish:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to container registry
        run: |
          echo $CONTAINER_TOKEN | docker login ghcr.io -u theislab --password-stdin
        env:
          CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
      -
        name: Build and run container
        run: |
          docker build . -t ghcr.io/theislab/extended-single-cell-best-practices-container:latest
          docker run ghcr.io/theislab/extended-single-cell-best-practices-container:latest
      -
        name: Push container to ghcr.io
        run: |
          docker push ghcr.io/theislab/extended-single-cell-best-practices-container:latest
          docker tag ghcr.io/theislab/extended-single-cell-best-practices-container:latest ghcr.io/theislab/extended-single-cell-best-practices-container:$RELEASE
          docker push ghcr.io/theislab/extended-single-cell-best-practices-container:$RELEASE
        env:
          RELEASE: ${{ github.event.release.tag_name }}